language: python
python:
  - 3.5

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python -m pytest --cov-report term-missing --cov=app
after_success:
  - coveralls
notifications:
  email: false

cache : pip
